(define (problem ferry) 
    (:init (place a) 
	   (place b)
	   (place c) 
	   (auto c1) 
	   (auto c2)
	   (auto c3)
	   (at c1 a)
	   (at c2 a)
	   (at c3 c)
	   (at-ferry b)
	   (empty-ferry))
  (:objects a b c c1 c2 c3)
  (:goal (and (at c1 b)
	      (at c2 b)
	      (at c3 b)))
  (:domain ferry))
